### ISSUE TITLE
Unable to import character since update

### ISSUE THREAD

**Issue by Rayquaza1090** [MrPrimate/pathmuncher#27] opened 2023-11-16 16:01 UTC
**Describe the bug**
When attempting to import a character from the Pathbuilder website, will get hung since the update.
Previously when attempting to use this, it got stuck on the weapon, which prompted me to update the addon, but now it will not go past ancestries. Attempting to uncheck the Ancestries box does nothing. Attempting to import the Json manually and removing the section to specify the Ancestry causes it to get stuck on the heritage instead.

**To Reproduce**
1. Go to pathbuilder website. If you want to use the antagonist I am, you can access him at https://pathbuilder2e.com/launch.html?build=590205
2. Click on Export to Json. Go into the Pathfinder 2e game world and attempt to import the code to an actor.
3. Enable Debug Logging

**Expected behavior**
Should have imported.

**Environment:**
 - Foundry Version Stable 315
 - Pathfinder System Version 5.9.1
 - Module Version [e.g 3.1.21]
 - Does this behaviour occur with other modules disabled: Yes
 - 
**Additional context**

 - In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.

https://pathbuilder2e.com/launch.html?build=590205

 - Details of any errors in the browser console (press F12).

undry.js:753 TypeError: Error thrown in hooked function 'renderActorSheetHook' for hook 'renderActorSheet'. Cannot read properties of undefined (reading 'type')
[Detected 2 packages: xdy-pf2e-workbench, system:pf2e]
    at _SkillAction.getData (skill-actions.ts:89:79)
    at sheet-skill-actions.ts:27:27
    at _SkillActionCollection.map (commons.js:4280:26)
    at renderActionsList (sheet-skill-actions.ts:26:10)
    at renderSheetSkillActions (sheet-skill-actions.ts:95:24)
    at Object.renderActorSheetHook [as fn] (hooks.ts:560:9)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at _CharacterSheetPF2e._render (foundry.js:5855:13)
    at async _CharacterSheetPF2e._render (foundry.js:6532:5)
    at async maintainFocusInRender (pf2e.mjs:6:78978)
    at async _CharacterSheetPF2e._render (pf2e.mjs:59:129589)
onError @ foundry.js:753
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
#call @ foundry.js:734
callAll @ foundry.js:687
_render @ foundry.js:5855
await in _render (async)
_render @ foundry.js:6532
(anonymous) @ pf2e.mjs:59
maintainFocusInRender @ pf2e.mjs:6
_render @ pf2e.mjs:59
render @ foundry.js:5769
render @ foundry.js:7111
render @ foundry.js:14259
_onUpdate @ foundry.js:14363
_onUpdate @ foundry.js:19131
_onUpdate @ pf2e.mjs:306
callback @ foundry.js:13737
(anonymous) @ foundry.js:13711
#handleUpdateDocuments @ foundry.js:13711
await in #handleUpdateDocuments (async)
_updateDocuments @ foundry.js:13458
await in _updateDocuments (async)
update @ commons.js:8677
await in update (async)
updateDocuments @ commons.js:8001
updateDocuments @ pf2e.mjs:306
await in updateDocuments (async)
update @ commons.js:8098
setFlags @ utils.js:42
_updateObject @ PathmuncherImporter.js:85
_onSubmit @ foundry.js:6626
foundry.js:6629 Error: This is not a registered game setting
    at ClientSettings.get (foundry.js:3339:42)
    at Pathmuncher.js:593:1
    at Array.find (<anonymous>)
    at #parsedFeatureMatch (Pathmuncher.js:576:1)
    at #findAllFeatureMatch (Pathmuncher.js:631:1)
    at #createGrantedItem (Pathmuncher.js:652:1)
    at #addGrantedItems (Pathmuncher.js:1176:1)
    at async #processGenericCompendiumLookup (Pathmuncher.js:530:1)
    at async Pathmuncher.processCharacter (Pathmuncher.js:2339:1)
    at async PathmuncherImporter._updateObject (PathmuncherImporter.js:104:1)
    at async PathmuncherImporter._onSubmit (foundry.js:6626:7)
_onSubmit @ foundry.js:6629

**Comment by MrPrimate** [comment] 2023-11-16 18:33
Duplicate of #26

**Closed by MrPrimate** 2023-11-16 18:33 UTC
Labels: bug
