### ISSUE TITLE
User cannot import their pathbuilder characters without create actor permissions even if their actor is already created

### ISSUE THREAD

**Issue by Ghilteras** [MrPrimate/pathmuncher#43] opened 2024-03-01 17:51 UTC
**Describe the bug**
User cannot import their pathbuilder characters without create actor permissions even if their actor is already created

**To Reproduce**
1. as a user open che character sheer
2. Click on pathmuncher import
3. input the code

**Expected behavior**
users should be able to import their pathbuilder character using their already created actor without requiring create actor permissions

**Comment by MrPrimate** [comment] 2024-03-01 20:18
Duplicate of  #9

**Closed by MrPrimate** 2024-03-01 20:18 UTC
Labels: bug
